# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/hello-world-ci

    docker:
      # specify the version you desire here
      - image: circleci/node:6.10
        environment:
          PGHOST: 127.0.0.1
          PGUSER: gl

      - image: circleci/postgres:9.6.2-alpine

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-cache

      - run:
          name: Install postgres cli
          command: sudo apt update && sudo apt install postgresql-client

      - run:
          name: check database before
          command: |
             psql -U postgres -c "\l"
             psql -U postgres -c "\du"

      - run:
          name: create database stuff
          command: |
            psql -U postgres -f create_db.sql
            psql -U postgres -d greenlight -f configure_db.sql

      - run:
          name: check database after
          command: |
             psql -U postgres -c "\l"
             psql -U postgres -c "\du"


      # deploy app

      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}
